In [2]:
myl1 = [101,201,301,401]
myl1+3 # vector operations cannot be performed on list

TypeError: can only concatenate list (not "int") to list

In [3]:
import numpy as mynp
mynp1_arr = mynp.array([101,201,301,401,501])
print(mynp1_arr+21) # vector operations will be performed on ndarray

[122 222 322 422 522]


In [4]:
import numpy as mynp
import sys

myl1 = [loop for loop in range(11,31)]
myndarray = mynp.array(myl1)
print('The List size is --> ',sys.getsizeof(myl1))
print('The ndarray size is a --> ',sys.getsizeof(myndarray))

The List size is -->  248
The ndarray size is a -->  192


In [5]:
import numpy as mynp
from datetime import datetime
myarr_1 = mynp.array([14,15,16])
myarr_2 = mynp.array([11,12,13])

In [14]:
#conventional Python code
def my_dot_product(myarr_1,myarr_2):
     my_result = 0
for _x,_y in zip(myarr_1,myarr_2):
     my_result += _x*_y
return my_result
mybefore_time = datetime.now()
for myloop in range(2000000):
    my_dot_product(myarr_1,myarr_2)
    myafter_time = datetime.now()
print('Time take to execute using conventional Python approach:',myafter_time-mybefore_time)

NameError: name 'my_result' is not defined

In [15]:
#code using numpy library
mybefore2_time = datetime.now()
for my_loop in range(2000000):
    mynp.dot(myarr_1,myarr_2) # using numpy
myafter2_time = datetime.now()
print('Time take to execute using Numpy Library:',myafter2_time-mybefore2_time)

Time take to execute using Numpy Library: 0:00:21.926362


In [ ]:
# creating a 1-D array using a list
import numpy as mynp
my_l1 = [113,213,313,413,567]
print(f'my_l1 type is: {type(my_l1)}')
mynd_arr = mynp.array(my_l1)
print('mynd_arr type is: --> '+ str(type(mynd_arr)))
print('mynd_arr -->'+ str(mynd_arr))
print('The Array dimensions is: '+ str(mynd_arr.ndim))
print('The data type of array elements is : '+ str(mynd_arr.dtype))
print('The array size is : '+ str(mynd_arr.size))
print('The array shape is : '+ str(mynd_arr.shape))

In [ ]:
# Creating a 1-D array using tuple
import numpy as mynp
mytuple = ('Ric','Pic','Tic','Mic')
print('mytuple type is: ' + str(type(mytuple)))
mynd_arr = mynp.array(mytuple)
print('mynd_arr type is: --> ' + str(type(mynd_arr)))
print('mynd_arr --> ' + str(mynd_arr))

In [ ]:
# creating a 2-D array using nested list
import numpy as mynp
my_nestedl1 = [[105,205,305],[405,505,605],
[705,805,905],[1005,1105,1205]]
mynd_arr = mynp.array(my_nestedl1)
print('mynd_arr type is: --> ' + str(type(mynd_arr)))
print('mynd_arr -->' + str(mynd_arr))
print('The array dimensions is:'+ str(mynd_arr.ndim))
print('The data type of array elements is : '+ str(mynd_arr.dtype))
print('The array size is :'+ str(mynd_arr.size))
print('The array shape is : ' + str(mynd_arr.shape))

In [ ]:
# list containing elements of different data type
import numpy as mynp
my_list = [201,301,420.5]
mynd_arr = mynp.array(my_list) # upcasting to float data type
print('mynd_arr -->'+str(mynd_arr))
print('Elements data type is --> ' + str(mynd_arr.dtype))

In [ ]:
import numpy as mynp
# int type
mynd_arr = mynp.array([101,201,410.8,0],dtype=int)
print(mynd_arr)
# float type
mynd_arr =
mynp.array([101,201,410.8,0],dtype=float)
print(mynd_arr)
# bool type : True for non-empty string and
number, False for empty string and 0
mynd_arr = mynp.array([101,201,410.8, 0,
'','BoolType','False'],dtype=bool)
print(mynd_arr)
# complex type
mynd_arr =
mynp.array([101,201,410.8,0],dtype=complex)
print(mynd_arr)
# str type
mynd_arr = mynp.array([101,201,410.8,0],dtype=str)
print(mynd_arr)

In [ ]:
import numpy as mynp
mynd_arr = mynp.array([410,'Yathartha',410.5,True,3+7j,False], dtype=object)
print(mynd_arr)
print('The elements data type of mynd_Arr is:' + str(mynd_arr.dtype))

In [ ]:
import numpy as mynp
mynd_arr = mynp.arange(7)
print('mynd_arr is:' + str(mynd_arr))
print('The array dimensions is: ' + str(mynd_arr.ndim))
print('The data type of elements of array is : ' + str(mynd_arr.dtype))

In [ ]:
print('The array size is : ' + str(mynd_arr.size))
print('The array shape is : ' + str(mynd_arr.shape))
print('-'*50)
mynd_arr1 = mynp.arange(1,7)
print('mynd_arr1 is:' + str(mynd_arr1))
print('The array dimensions is: ' + str(mynd_arr1.ndim))
print('The data type of elements of array is : ' + str(mynd_arr1.dtype))
print('The array size is : ' + str(mynd_arr1.size))
print('The array shape is : ' + str(mynd_arr1.shape))
print('-'*50)
mynd_arr2 = mynp.arange(1,7,2)
print('mynd_arr is:' + str(mynd_arr2))

In [ ]:
print('The array dimensions is: ' + str(mynd_arr2.ndim))
print('The data type of elements of array is : ' + str(mynd_arr2.dtype))
print('The array size is : ' + str(mynd_arr2.size))
print('The array shape is : ' + str(mynd_arr2.shape))
print('-'*50)
mynd_arr3 = mynp.arange(1,7,3,dtype=float)
print('mynd_arr is:' + str(mynd_arr3))
print('The array dimensions is: ' + str(mynd_arr3.ndim))
print('The data type of elements of array is : ' + str(mynd_arr3.dtype))
print('The array size is : ' + str(mynd_arr3.size))
print('The array shape is : ' + str(mynd_arr3.shape))

In [ ]:
import numpy as mynp
# evenly spaced values of no. of samples as 50 between 0 and 2 which includes both 0 and 2
print(mynp.linspace(0,2))
print('-'*50)
# 3 evenly spaced values between 0 and 2 and also including both 0 and 2
print(mynp.linspace(0,2,3))
print('-'*50)
# 3 evenly spaced values between 0 and 2 and also including 0 but excluding 2
print(mynp.linspace(0,2,3, endpoint=False))

In [ ]:
print('-'*50)
# 3 evenly spaced values between 0 and 2 and also including 0 but excluding 2 and also returning spacing
print(mynp.linspace(0,2,3, endpoint=False,
retstep=True))
print('-'*50)
# 5 values between 2 to 50 including both 2 and 50 with equally spacing int type values with spacing as 12.0
print(mynp.linspace(2,50,5, dtype=int, retstep=True))

In [ ]:
import numpy as mynp

# Creating 1-D array with zeros
print(mynp.zeros(4))
print('-'*50)
# Creating 2-D array with zeros
print(mynp.zeros((4,4)))
print('-'*50)
# Creating 3-D array with zeros
print(mynp.zeros((2,3,2)))
print('-'*50)
# Creating 4-D array with zeros
print(mynp.zeros((3,1,2,3)))

In [ ]:
import numpy as mynp

# Creating 1-D array with ones
print(mynp.ones(4))
print('-'*50)
# Creating 2-D array with ones
print(mynp.ones((4,2), dtype = int))
print('-'*50)
# Creating 3-D array with ones
print(mynp.ones((3,2,4), dtype = int))

In [ ]:
import numpy as mynp

print(help(mynp.full))

In [ ]:
import numpy as mynp

# Creating 1-D array
print(mynp.full(shape=4,fill_value=2))
print('-'*50)
# Creating 2-D array
print(mynp.full((3,2),fill_value=2))
print('-'*50)
# Creating 3-D array
print(mynp.full((3,2,3),2)) # fill_value here is 2

In [ ]:
import numpy as mynp

print(help(mynp.eye))

In [ ]:
import numpy as mynp

# Creating 2-D array with default value k = 0
print(mynp.eye(2,4))
print('-'*50)
# Creating 2-D array with k = 1
print(mynp.eye(5, k=1))
print('-'*50)
# Creating 2-D array with k = 2
print(mynp.eye(5, k=2))
print('-'*50)
# Creating 2-D array with k = -1
print(mynp.eye(5, k=-1))
print('-'*50)
# Creating 2-D array with k = -2
print(mynp.eye(5, k=-2))

In [ ]:
import numpy as mynp

print(help(mynp.diag))

In [ ]:
import numpy as mynp
# Extracting 2-D diagonal elements
myndarray = mynp.arange(17,33).reshape(4,4)
print("2-D Original array is : \n " + str(myndarray))
print("The elements present at 0-diagonal : " + str(mynp.diag(myndarray,k=0)))
print("The elements present at 1-diagonal : " + str(mynp.diag(myndarray,k=1)))
print("The elements present at 2-diagonal : " + str(mynp.diag(myndarray,k=2)))
print("The elements present at -1-diagonal : " + str(mynp.diag(myndarray,k=-1)))
print("The elements present at -2-diagonal : " + str(mynp.diag(myndarray,k=-2)))
print("The elements present at 3-diagonal : " + str(mynp.diag(myndarray,k=3)))
print("The elements present at -3-diagonal : " + str(mynp.diag(myndarray,k=-3)))
print('-'*50)


# 1-D construct a 2-D array using the provided elements and a diagonal array;
# and here the remaining elements are all filled with zeros.
mynd_arr1 = mynp.array([101,201,301,401,501])
print(mynp.diag(mynd_arr1,k=0))
print('-'*50)
mynd_arr2 = mynp.array([101,201,301,401,501])
print(mynp.diag(mynd_arr2,k=1))
print('-'*50)
mynd_arr3 = mynp.array([101,201,301,401,501])
print(mynp.diag(mynd_arr3,k=-1))

In [ ]:
import numpy as mynp
print(mynp.empty((4,3)))

In [ ]:
# np.random module examples
import numpy as mynp
import sys
# single random integer value generation in the range between 20 to 29
print(mynp.random.randint(20,30))
print('-'*50)
# 1-D nd-array creation of size 5 with random values from 10 to 19
print(mynp.random.randint(10,20, size=5))
print('-'*50)
# 2-D array with high as None and random values from 0 to 49 with shape as (3,4)
print(mynp.random.randint(0,50, size=(3,4)))
print('-'*50)
# memory utilization is improved using dtype
a = mynp.random.randint(1,21,size=(30,40))
print(f"ndarray int32 size: {sys.getsizeof(a)}")
a = mynp.random.randint(1,21,size=(30,40),dtype='int8')
print(f"ndarray int8 size : {sys.getsizeof(a)}")

In [ ]:
import numpy as mynp
# print(help(mynp.random.shuffle)) # This will
display help of shuffle function
# shuffling of 1-D array
mynp1 = mynp.arange(6)
print(f'before shuffle mynp1 data is {mynp1}')
mynp.random.shuffle(mynp1)
print(f'after shuffle mynp1 data is {mynp1}')
print('-'*50)
# shuffling of 2-D array -- shuffling around axis0
mynp2 = mynp.random.randint(1,50,size=(4,3))
print(f'before shuffle mynp2 data is {mynp2}')
mynp.random.shuffle(mynp2)
print(f'after shuffle mynp2 data is {mynp2}')

In [ ]:
import numpy as mynp
# Example of view
mynp1=mynp.array([16,28,37,46,55])
mynp2=mynp1.view()
print(f"The original array is: {mynp1}")
print(f"The view array is: {mynp2}")
print('-'*50)
mynp1[2]=100
print(f"After changing 2nd index value of mynp1, mynp1 array value is changed as: {mynp1}")
print(f"After changing 2nd index value of mynp1, mynp2 array value is changed as: {mynp2}")
print('-'*50)
mynp2[-1]=300
print(f"After changing last index value of mynp2, mynp1 array value is changed as: {mynp1}")

print(f"After changing last index value of mynp2, mynp2 array value is changed as: {mynp2}")
# Example of copy
print('*'*100)
mynp3=mynp.array([111,132,136,147,158])
mynp4=mynp3.copy()
print(f"The original array is: {mynp3}")
print(f"The copy array is: {mynp4}")
print('-'*50)
mynp3[2]=110
print(f"After changing 2nd index value of mynp3, mynp3 array value is changed as: {mynp3}")
print(f"After changing 2nd index value of mynp3, mynp4 array value is retained as: {mynp4}")
print('-'*50)
mynp4[-1]=310
print(f"After changing last index value of mynp4, mynp3 array value is retained as: {mynp3}")
print(f"After changing last index value of mynp4, mynp4 array value is changed as: {mynp4}")

In [ ]:
import numpy as mynp
# We will be accessing elements of 3-D numpy array
mynd1 = mynp.array([
 [[111,112,113],[114,115,116],[117,118,119]],
 [[11,21,31],[41,51,61],[71,81,91]]])


# 1. using indexing: single element access, zero based indexing supporting both +ve and -ve
print(f"Array shape is: ==> {mynd1.shape}")
print("To access the element 19 from the 3-D array")
print(f"mynd1[0][2][2] ==> {mynd1[0][2][2]}")
print(f"mynd1[-2][-1][-1] ==> {mynd1[-2][-1][-1]}")
print('-'*50)


# 2. using slicing: elements group which are in order
print("Accessing elements: 0th and 2nd row of 0th and 2nd column value of each 2-D array")
print(f"mynd1[:,::2,::2] ==> {mynd1[:,::2,::2]}")
print('-'*50) 
# 3. using advanced indexing: elements group which are not ordered (arbitrary elements)
# In order to access 3-D array arbitrary elements use
e
# myndarray[[2-D array indices],[row indices], [column indices]]
print("To access element 15 and 5 from 3-D array")
print(mynd1[[0,1],[1,1],[1,1]])
print('-'*50) 
# 4. using condition based selection: selecting array elements based on condition
mynp2=mynp.arange(11,23).reshape(3,4)
print(mynp2[mynp2%2 !=0]) # displaying odd numbers from an array as condition will return the boolean value
# and array[condition] will return the result

In [ ]:
import numpy as mynp

# Approach1: iteration using Python loop 
# we are iterating elements of 3-D array
myarr1 = mynp.array([[[34,44],[54,64]],[[74,84],[94,104]]])
for outer in myarr1: #iterating 2-D array with no scalar value
 for inner in outer: # iterating 1-D array with no scalar value
 for data in inner: # here data is a scalar value
 print(data)
print('-'*50))

# Approach2: iteration using nditer() function:
# class in numpy library with only one loop for iterating any n-D array
myarr2=mynp.arange(21,27).reshape(2,3)
for loop in mynp.nditer(myarr2):
 print(loop)
print('-'*50)
# Approach3: iteration using ndenumerate() function
# This function will return indexes in addition to elements as multidimensional
# index iterator will be returned yielding pair of index-tuple with the corresponding array values
for mypos,myelement in mynp.ndenumerate(myarr2):
 print(f'{myelement} is present at position:{mypos}')   

In [ ]:
import numpy as mynp
myarr1 = mynp.array([ [21,31,41], [52,62,72] ])
myarr2 = mynp.arange(21,27).reshape(2,3)
print(f"Dimension of myarr1 is : {myarr1.ndim}, size of myarr1 is :{myarr1.size} 
and shape of myarr1 is : {myarr1.shape}")

print(f"Dimension of myarr2 is : {myarr2.ndim},
size of myarr2 is :{myarr2.size} and shape of
myarr2 is : {myarr2.shape}")
print(f'Numpy array 1 is: {myarr1}')
print(f'Numpy array 2 is: {myarr2}')

# performing addition
print('-'*50)
print(f"Addition of 2 numpy arrays is{mynp.add(myarr1,myarr2)}")
# performing subtraction
print('-'*50)
print(f"Subtraction of 2 numpy arrays is{mynp.subtract(myarr1,myarr2)}")
# performing multiplication
print('-'*50)
print(f"Multiplication of 2 numpy arrays is{mynp.multiply(myarr1,myarr2)}")
# performing division
print('-'*50)
print(f"Division of 2 numpy arrays is
{mynp.divide(myarr1,myarr2)}")
# performing floor division
print('-'*50)
print(f"Floor division of 2 numpy arrays is{mynp.floor_divide(myarr1,myarr2)}")
# performing modulus
print('-'*50)
print(f"Modulus of 2 numpy arrays is{mynp.mod(myarr1,myarr2)}")
# performing power
print('-'*50)
print(f"Power of 2 numpy arrays is{mynp.power(myarr1,myarr2)}")

In [ ]:
import numpy as mynp

print("Broadcasting of 1-D array--------------")
# Broadcasting of 1-D array
myarr1=mynp.array([21,22,23])
myarr2= mynp.array([10])
print(f"myarr1 is {myarr1}")
print(f"myarr2 is {myarr2}")
print(f"myarr1+myarr2 is: {myarr1+myarr2}")

# myarr1 is [21 22 23]
# on broadcasting myarr2 becomes [10 10 10]
# answer becomes [31 32 33]
print("Broadcasting of 2-D array--------------")
myarr3= mynp.arange(21,27).reshape(2,3)
myarr4= mynp.array([10,12,13])
print(f"myarr3 is {myarr3}")
print(f"myarr4 is {myarr4}")
print(f"myarr3+myarr4 is: {myarr3+myarr4}")
# myarr3 is [21 22 23]
# [24 25 26]
# on broadcasting myarr4 becomes [10 12 13]
# [10 12 13]
# answer becomes [31 34 36]


Happy Programming